WARNING 2018-05-03 11:44:00,975 farmzone.core.models User 1 didn't have any phone_number marked as primary falling back to return first number
INFO 2018-05-03 11:44:00,977 farmzone.core.models Contact for the user: Arun Singhal#1 is 9891077610
WARNING 2018-05-03 11:44:00,985 farmzone.core.models User 1 didn't have any phone_number marked as primary falling back to return first number
INFO 2018-05-03 11:44:00,987 farmzone.core.models Contact for the user: Arun Singhal#1 is 9891077610
WARNING 2018-05-03 11:45:28,277 farmzone.core.models User 1 didn't have any phone_number marked as primary falling back to return first number
INFO 2018-05-03 11:45:28,279 farmzone.core.models Contact for the user: Arun Singhal#1 is 9891077610
WARNING 2018-05-03 11:54:54,162 farmzone.core.models User 1 didn't have any phone_number marked as primary falling back to return first number
INFO 2018-05-03 11:54:54,164 farmzone.core.models Contact for the user: Arun Singhal#1 is 9891077610
WARNING 2018-05-03 11:54:54,174 farmzone.core.models User 1 didn't have any phone_number marked as primary falling back to return first number
INFO 2018-05-03 11:54:54,176 farmzone.core.models Contact for the user: Arun Singhal#1 is 9891077610
WARNING 2018-05-03 11:54:55,167 farmzone.core.models User 1 didn't have any phone_number marked as primary falling back to return first number
INFO 2018-05-03 11:54:55,170 farmzone.core.models Contact for the user: Arun Singhal#1 is 9891077610
WARNING 2018-05-03 11:54:55,180 farmzone.core.models User 1 didn't have any phone_number marked as primary falling back to return first number
INFO 2018-05-03 11:54:55,182 farmzone.core.models Contact for the user: Arun Singhal#1 is 9891077610
WARNING 2018-05-03 11:54:55,822 farmzone.core.models User 1 didn't have any phone_number marked as primary falling back to return first number
INFO 2018-05-03 11:54:55,824 farmzone.core.models Contact for the user: Arun Singhal#1 is 9891077610
WARNING 2018-05-03 11:54:55,831 farmzone.core.models User 1 didn't have any phone_number marked as primary falling back to return first number
INFO 2018-05-03 11:54:55,832 farmzone.core.models Contact for the user: Arun Singhal#1 is 9891077610
WARNING 2018-05-03 11:54:56,178 farmzone.core.models User 1 didn't have any phone_number marked as primary falling back to return first number
INFO 2018-05-03 11:54:56,179 farmzone.core.models Contact for the user: Arun Singhal#1 is 9891077610
WARNING 2018-05-03 11:54:56,188 farmzone.core.models User 1 didn't have any phone_number marked as primary falling back to return first number
INFO 2018-05-03 11:54:56,190 farmzone.core.models Contact for the user: Arun Singhal#1 is 9891077610
WARNING 2018-05-03 11:54:56,476 farmzone.core.models User 1 didn't have any phone_number marked as primary falling back to return first number
INFO 2018-05-03 11:54:56,478 farmzone.core.models Contact for the user: Arun Singhal#1 is 9891077610
WARNING 2018-05-03 11:54:56,485 farmzone.core.models User 1 didn't have any phone_number marked as primary falling back to return first number
INFO 2018-05-03 11:54:56,488 farmzone.core.models Contact for the user: Arun Singhal#1 is 9891077610
WARNING 2018-05-03 11:54:56,764 farmzone.core.models User 1 didn't have any phone_number marked as primary falling back to return first number
INFO 2018-05-03 11:54:56,766 farmzone.core.models Contact for the user: Arun Singhal#1 is 9891077610
WARNING 2018-05-03 11:54:56,774 farmzone.core.models User 1 didn't have any phone_number marked as primary falling back to return first number
INFO 2018-05-03 11:54:56,776 farmzone.core.models Contact for the user: Arun Singhal#1 is 9891077610
WARNING 2018-05-03 11:54:56,991 farmzone.core.models User 1 didn't have any phone_number marked as primary falling back to return first number
INFO 2018-05-03 11:54:56,993 farmzone.core.models Contact for the user: Arun Singhal#1 is 9891077610
WARNING 2018-05-03 11:54:57,000 farmzone.core.models User 1 didn't have any phone_number marked as primary falling back to return first number
INFO 2018-05-03 11:54:57,001 farmzone.core.models Contact for the user: Arun Singhal#1 is 9891077610
WARNING 2018-05-03 11:54:57,202 farmzone.core.models User 1 didn't have any phone_number marked as primary falling back to return first number
INFO 2018-05-03 11:54:57,204 farmzone.core.models Contact for the user: Arun Singhal#1 is 9891077610
WARNING 2018-05-03 11:54:57,212 farmzone.core.models User 1 didn't have any phone_number marked as primary falling back to return first number
INFO 2018-05-03 11:54:57,214 farmzone.core.models Contact for the user: Arun Singhal#1 is 9891077610
WARNING 2018-05-03 11:54:57,501 farmzone.core.models User 1 didn't have any phone_number marked as primary falling back to return first number
INFO 2018-05-03 11:54:57,503 farmzone.core.models Contact for the user: Arun Singhal#1 is 9891077610
WARNING 2018-05-03 11:54:57,511 farmzone.core.models User 1 didn't have any phone_number marked as primary falling back to return first number
INFO 2018-05-03 11:54:57,512 farmzone.core.models Contact for the user: Arun Singhal#1 is 9891077610
WARNING 2018-05-03 11:55:08,689 farmzone.core.models User 1 didn't have any phone_number marked as primary falling back to return first number
INFO 2018-05-03 11:55:08,690 farmzone.core.models Contact for the user: Arun Singhal#1 is 9891077610
WARNING 2018-05-03 11:55:09,589 farmzone.core.models User 1 didn't have any phone_number marked as primary falling back to return first number
INFO 2018-05-03 11:55:09,591 farmzone.core.models Contact for the user: Arun Singhal#1 is 9891077610
WARNING 2018-05-03 11:55:10,633 farmzone.core.models User 1 didn't have any phone_number marked as primary falling back to return first number
INFO 2018-05-03 11:55:10,634 farmzone.core.models Contact for the user: Arun Singhal#1 is 9891077610
WARNING 2018-05-03 11:55:11,148 farmzone.core.models User 1 didn't have any phone_number marked as primary falling back to return first number
INFO 2018-05-03 11:55:11,149 farmzone.core.models Contact for the user: Arun Singhal#1 is 9891077610
WARNING 2018-05-03 11:55:11,406 farmzone.core.models User 1 didn't have any phone_number marked as primary falling back to return first number
INFO 2018-05-03 11:55:11,408 farmzone.core.models Contact for the user: Arun Singhal#1 is 9891077610
ERROR 2018-05-03 11:57:09,411 django.request Internal Server Error: /api/1.0.0/seller/S0002/pending_queries/
Traceback (most recent call last):
  File "/home/arun/software/venv/lib/python3.5/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/home/arun/software/venv/lib/python3.5/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/arun/software/venv/lib/python3.5/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/arun/software/venv/lib/python3.5/site-packages/django/views/decorators/csrf.py", line 58, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/arun/software/venv/lib/python3.5/site-packages/rest_framework/viewsets.py", line 86, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/arun/software/venv/lib/python3.5/site-packages/rest_framework/views.py", line 489, in dispatch
    response = self.handle_exception(exc)
  File "/home/arun/software/venv/lib/python3.5/site-packages/rest_framework/views.py", line 449, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/home/arun/software/venv/lib/python3.5/site-packages/rest_framework/views.py", line 486, in dispatch
    response = handler(request, *args, **kwargs)
  File "/home/arun/software/venv/lib/python3.5/site-packages/rest_framework/mixins.py", line 40, in list
    queryset = self.filter_queryset(self.get_queryset())
  File "/home/arun/software/mystuff/git/platform-service/farmzone/sellers/views/support.py", line 14, in get_queryset
    return get_seller_queries_without_status(seller_code, SupportStatus.RESOLVED.value)
  File "/home/arun/software/mystuff/git/platform-service/farmzone/qms/query.py", line 13, in get_seller_queries_without_status
    return Support.objects.select_related('support_category').filter(seller__seller_code=seller_code)\
  File "/home/arun/software/venv/lib/python3.5/site-packages/django/db/models/query.py", line 782, in filter
    return self._filter_or_exclude(False, *args, **kwargs)
  File "/home/arun/software/venv/lib/python3.5/site-packages/django/db/models/query.py", line 800, in _filter_or_exclude
    clone.query.add_q(Q(*args, **kwargs))
  File "/home/arun/software/venv/lib/python3.5/site-packages/django/db/models/sql/query.py", line 1261, in add_q
    clause, _ = self._add_q(q_object, self.used_aliases)
  File "/home/arun/software/venv/lib/python3.5/site-packages/django/db/models/sql/query.py", line 1287, in _add_q
    allow_joins=allow_joins, split_subq=split_subq,
  File "/home/arun/software/venv/lib/python3.5/site-packages/django/db/models/sql/query.py", line 1165, in build_filter
    lookups, parts, reffed_expression = self.solve_lookup_type(arg)
  File "/home/arun/software/venv/lib/python3.5/site-packages/django/db/models/sql/query.py", line 1045, in solve_lookup_type
    _, field, _, lookup_parts = self.names_to_path(lookup_splitted, self.get_meta())
  File "/home/arun/software/venv/lib/python3.5/site-packages/django/db/models/sql/query.py", line 1363, in names_to_path
    "Choices are: %s" % (name, ", ".join(available)))
django.core.exceptions.FieldError: Cannot resolve keyword 'seller' into field. Choices are: comment, created_at, id, seller_sub_product, seller_sub_product_id, status, support_category, support_category_id, updated_at, user, user_id
ERROR 2018-05-03 11:57:09,497 django.server "GET /api/1.0.0/seller/S0002/pending_queries/ HTTP/1.1" 500 152399
WARNING 2018-05-03 12:00:36,077 farmzone.core.models User 1 didn't have any phone_number marked as primary falling back to return first number
INFO 2018-05-03 12:00:36,078 farmzone.core.models Contact for the user: Arun Singhal#1 is 9891077610
INFO 2018-05-03 13:16:45,668 farmzone.buyers.views.support Manadatory fields missing. Requested params {}
ERROR 2018-05-03 13:16:45,681 django.request Internal Server Error: /api/1.0.0/buyer/1/save_query/
Traceback (most recent call last):
  File "/home/arun/software/venv/lib/python3.5/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/home/arun/software/venv/lib/python3.5/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/arun/software/venv/lib/python3.5/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/arun/software/venv/lib/python3.5/site-packages/django/views/decorators/csrf.py", line 58, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/arun/software/venv/lib/python3.5/site-packages/django/views/generic/base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/arun/software/venv/lib/python3.5/site-packages/rest_framework/views.py", line 489, in dispatch
    response = self.handle_exception(exc)
  File "/home/arun/software/venv/lib/python3.5/site-packages/rest_framework/views.py", line 449, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/home/arun/software/venv/lib/python3.5/site-packages/rest_framework/views.py", line 486, in dispatch
    response = handler(request, *args, **kwargs)
  File "/home/arun/software/mystuff/git/platform-service/farmzone/buyers/views/support.py", line 39, in post
    status.HTTP_400_BAD_REQUEST)
AttributeError: 'str' object has no attribute 'HTTP_400_BAD_REQUEST'
ERROR 2018-05-03 13:16:45,738 django.server "POST /api/1.0.0/buyer/1/save_query/ HTTP/1.1" 500 109189
INFO 2018-05-03 13:18:01,991 farmzone.buyers.views.support Manadatory fields missing. Requested params {}
ERROR 2018-05-03 13:18:01,994 django.request Internal Server Error: /api/1.0.0/buyer/1/save_query/
Traceback (most recent call last):
  File "/home/arun/software/venv/lib/python3.5/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/home/arun/software/venv/lib/python3.5/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/arun/software/venv/lib/python3.5/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/arun/software/venv/lib/python3.5/site-packages/django/views/decorators/csrf.py", line 58, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/arun/software/venv/lib/python3.5/site-packages/django/views/generic/base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/arun/software/venv/lib/python3.5/site-packages/rest_framework/views.py", line 489, in dispatch
    response = self.handle_exception(exc)
  File "/home/arun/software/venv/lib/python3.5/site-packages/rest_framework/views.py", line 449, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/home/arun/software/venv/lib/python3.5/site-packages/rest_framework/views.py", line 486, in dispatch
    response = handler(request, *args, **kwargs)
  File "/home/arun/software/mystuff/git/platform-service/farmzone/buyers/views/support.py", line 40, in post
    status.HTTP_400_BAD_REQUEST)
AttributeError: 'str' object has no attribute 'HTTP_400_BAD_REQUEST'
ERROR 2018-05-03 13:18:02,047 django.server "POST /api/1.0.0/buyer/1/save_query/ HTTP/1.1" 500 109189
INFO 2018-05-03 13:19:10,904 farmzone.buyers.views.support Manadatory fields missing. Requested params {}
INFO 2018-05-03 13:19:45,700 farmzone.buyers.views.support support_category_id does not match any support category 10
INFO 2018-05-03 13:20:07,832 farmzone.buyers.views.support Processing Request to add query for user 1 & buyer 1
INFO 2018-05-03 13:20:07,832 farmzone.support.models Creating new support entry for user 1 
INFO 2018-05-03 13:21:24,826 farmzone.buyers.views.support seller_sub_product_id does not match any seller_sub_product 1000
INFO 2018-05-03 13:21:34,147 farmzone.buyers.views.support seller_sub_product_id does not match any seller_sub_product 73
INFO 2018-05-03 13:21:59,435 farmzone.buyers.views.support Processing Request to add query for user 1 & buyer 1
INFO 2018-05-03 13:21:59,435 farmzone.support.models Creating new support entry for user 1 
INFO 2018-05-03 13:22:45,650 farmzone.buyers.views.support Processing Request to add query for user 1 & buyer 1
INFO 2018-05-03 13:22:45,650 farmzone.support.models Creating new support entry for user 1 
WARNING 2018-05-03 13:24:20,475 farmzone.core.models User 1 didn't have any phone_number marked as primary falling back to return first number
INFO 2018-05-03 13:24:20,477 farmzone.core.models Contact for the user: Arun Singhal#1 is 9891077610
WARNING 2018-05-03 13:24:21,932 farmzone.core.models User 1 didn't have any phone_number marked as primary falling back to return first number
INFO 2018-05-03 13:24:21,933 farmzone.core.models Contact for the user: Arun Singhal#1 is 9891077610
WARNING 2018-05-03 13:24:36,100 farmzone.core.models User 1 didn't have any phone_number marked as primary falling back to return first number
INFO 2018-05-03 13:24:36,102 farmzone.core.models Contact for the user: Arun Singhal#1 is 9891077610
WARNING 2018-05-03 13:24:36,984 farmzone.core.models User 1 didn't have any phone_number marked as primary falling back to return first number
INFO 2018-05-03 13:24:36,986 farmzone.core.models Contact for the user: Arun Singhal#1 is 9891077610
WARNING 2018-05-03 13:29:29,560 farmzone.core.models User 1 didn't have any phone_number marked as primary falling back to return first number
INFO 2018-05-03 13:29:29,562 farmzone.core.models Contact for the user: Arun Singhal#1 is 9891077610
WARNING 2018-05-03 13:29:40,001 farmzone.core.models User 1 didn't have any phone_number marked as primary falling back to return first number
INFO 2018-05-03 13:29:40,003 farmzone.core.models Contact for the user: Arun Singhal#1 is 9891077610
INFO 2018-05-03 14:25:03,691 farmzone.buyers.views.support Manadatory fields missing. Requested params {}
INFO 2018-05-03 14:25:16,853 farmzone.buyers.views.support query_id does not match any support query 100
INFO 2018-05-03 14:25:41,786 farmzone.buyers.views.support Support status is not in accepted state to resolve NEW
INFO 2018-05-03 14:26:27,902 farmzone.buyers.views.support Processing Request to accept query for user 1 & buyer 1
INFO 2018-05-03 14:32:45,845 farmzone.sellers.views.support Manadatory fields missing. Requested params {}
INFO 2018-05-03 14:32:58,819 farmzone.sellers.views.support query_id does not match any support query 200
INFO 2018-05-03 14:33:13,463 farmzone.sellers.views.support query_id does not match any support query 1
ERROR 2018-05-03 14:33:50,785 django.request Internal Server Error: /api/1.0.0/seller/S0002/accept_query/
Traceback (most recent call last):
  File "/home/arun/software/venv/lib/python3.5/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/home/arun/software/venv/lib/python3.5/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/arun/software/venv/lib/python3.5/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/arun/software/venv/lib/python3.5/site-packages/django/views/decorators/csrf.py", line 58, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/arun/software/venv/lib/python3.5/site-packages/django/views/generic/base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/arun/software/venv/lib/python3.5/site-packages/rest_framework/views.py", line 489, in dispatch
    response = self.handle_exception(exc)
  File "/home/arun/software/venv/lib/python3.5/site-packages/rest_framework/views.py", line 449, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/home/arun/software/venv/lib/python3.5/site-packages/rest_framework/views.py", line 486, in dispatch
    response = handler(request, *args, **kwargs)
  File "/home/arun/software/mystuff/git/platform-service/farmzone/sellers/views/support.py", line 50, in post
    logger.info("Processing Request to accept query for user {0} & buyer {1}".format(request.user.id, user_id))
NameError: name 'user_id' is not defined
ERROR 2018-05-03 14:33:50,838 django.server "POST /api/1.0.0/seller/S0002/accept_query/ HTTP/1.1" 500 108809
INFO 2018-05-03 14:34:32,720 farmzone.sellers.views.support Processing Request to accept query for user 1 & seller S0002
INFO 2018-05-03 14:34:59,262 farmzone.sellers.views.support Support status is not in New state to accept ACCEPTED
INFO 2018-05-03 14:35:20,755 farmzone.sellers.views.support Processing Request to accept query for user 1 & seller S0002
INFO 2018-05-03 14:37:12,964 farmzone.buyers.views.order Processing request to fetch completed orders for user 1 user_id 1
INFO 2018-05-03 15:42:57,780 farmzone.buyers.views.support Processing Request to add query for user 1 & buyer 1
INFO 2018-05-03 15:42:57,780 farmzone.support.models Creating new support entry for user 1 
INFO 2018-05-03 15:43:14,716 farmzone.buyers.views.support order_detail_id does not match any order_detail 350
INFO 2018-05-03 15:43:22,643 farmzone.buyers.views.support order_detail_id does not match any order_detail 35
INFO 2018-05-03 15:43:38,452 farmzone.buyers.views.support Processing Request to add query for user 1 & buyer 1
INFO 2018-05-03 15:43:38,452 farmzone.support.models Creating new support entry for user 1 
INFO 2018-05-03 15:48:03,463 farmzone.sellers.views.support Processing Request to accept query for user 1 & seller S0002
INFO 2018-05-03 15:48:54,907 farmzone.buyers.views.support Manadatory fields missing. Requested params {'query_id': 8}
INFO 2018-05-03 15:49:07,971 farmzone.buyers.views.support Processing Request to resolve query for user 1 & buyer 1
WARNING 2018-05-03 15:49:29,262 farmzone.core.models User 1 didn't have any phone_number marked as primary falling back to return first number
INFO 2018-05-03 15:49:29,265 farmzone.core.models Contact for the user: Arun Singhal#1 is 9891077610
WARNING 2018-05-03 15:49:29,274 farmzone.core.models User 1 didn't have any phone_number marked as primary falling back to return first number
INFO 2018-05-03 15:49:29,277 farmzone.core.models Contact for the user: Arun Singhal#1 is 9891077610
WARNING 2018-05-03 15:49:29,286 farmzone.core.models User 1 didn't have any phone_number marked as primary falling back to return first number
INFO 2018-05-03 15:49:29,288 farmzone.core.models Contact for the user: Arun Singhal#1 is 9891077610
WARNING 2018-05-03 15:49:29,297 farmzone.core.models User 1 didn't have any phone_number marked as primary falling back to return first number
INFO 2018-05-03 15:49:29,299 farmzone.core.models Contact for the user: Arun Singhal#1 is 9891077610
WARNING 2018-05-03 15:49:29,306 farmzone.core.models User 1 didn't have any phone_number marked as primary falling back to return first number
INFO 2018-05-03 15:49:29,308 farmzone.core.models Contact for the user: Arun Singhal#1 is 9891077610
WARNING 2018-05-03 15:49:46,204 farmzone.core.models User 1 didn't have any phone_number marked as primary falling back to return first number
INFO 2018-05-03 15:49:46,205 farmzone.core.models Contact for the user: Arun Singhal#1 is 9891077610
WARNING 2018-05-03 15:49:46,216 farmzone.core.models User 1 didn't have any phone_number marked as primary falling back to return first number
INFO 2018-05-03 15:49:46,217 farmzone.core.models Contact for the user: Arun Singhal#1 is 9891077610
WARNING 2018-05-03 15:49:46,224 farmzone.core.models User 1 didn't have any phone_number marked as primary falling back to return first number
INFO 2018-05-03 15:49:46,226 farmzone.core.models Contact for the user: Arun Singhal#1 is 9891077610
WARNING 2018-05-03 15:49:58,796 farmzone.core.models User 1 didn't have any phone_number marked as primary falling back to return first number
INFO 2018-05-03 15:49:58,798 farmzone.core.models Contact for the user: Arun Singhal#1 is 9891077610
